name: Build iOS App
on:
  push:
    branches: [ main ] # This triggers whenever you "git push" to your fork

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync ios

      - name: Build iOS Project
        run: npx cap build ios --no-open

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-data
          path: ios/App/